# Generated by Django 4.2.4 on 2023-10-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='massage',
            new_name='matn',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='nam',
        ),
    ]
